### ISSUE TITLE
replacing previous import ‘utils::findMatches’ by ‘S4Vectors::findMatches’ when loading ‘AnnotationDbi’

### ISSUE THREAD

**Issue by lambdamoses** [Bioconductor/AnnotationDbi#11]
In Bioconductor 3.17, when I call `library(AnnotationDbi)`, or loading a package that imports AnnotationDbi, I get this warning:

```
Warning message:
replacing previous import ‘utils::findMatches’ by ‘S4Vectors::findMatches’ when loading ‘AnnotationDbi’
```

I'm running R 4.3.0 on MacOS 13.3.1

**Comment by mjsteinbaugh** [comment]
I'm seeing this pop up as well -- can we rename to `findMatches2` or some other approach to avoid masking utils?

**Comment by LiNk-NY** [comment]
This was added to R not too long ago: 
https://github.com/wch/r-source/commit/32fd909429c8ded78309a4893d784efd92dc930c 
The issue should be in the `S4Vectors` repo. 
-MR

**Comment by mjsteinbaugh** [comment]
OK posted at Bioconductor support here:
https://support.bioconductor.org/p/9151164/

Safe to close

**Comment by hpages** [comment]
Fixed in the latest version of **AnnotationDbi**: ccc9f424fa361e2e2378ba4d407763c32fc10642

**Comment by mjsteinbaugh** [comment]
Boom thanks @hpages !
