### ISSUE TITLE
hom.Rn.inp.db is  required but removed from bioconductor release

### ISSUE THREAD

**Issue by shanie-landen** [Bioconductor/AnnotationDbi#14]
I am trying to convert rat genes to human gene orthologs using idConverter() however when running the code I get an error that loading of hom.Rn.inp.db and is required, however this has been removed from bioconductor and I would like to make sure that my ortholog retrieval is up to date, trustworthy, and replicable so I don't want to be installing later deprecated packages.

Code:
```
orthologs=idConverter(ids=allrats_sigs$NOG,
                      srcSpecies = "RATNO",
                      destSpecies = "HOMSA",
                      srcIDType ="ENSEMBL" )
```

Error:

```
Loading required package: hom.Rn.inp.db
Error in get(paste0("hom.", srcSpcAbrv, ".inp", destSpecies)) : 
  object 'hom.Rn.inpHOMSA' not found
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called 'hom.Rn.inp.db'
```

**Comment by jmacdon** [comment]
Please don't use the issue tracker for support. There is a dedicated support site at support.bioconductor.org that you can use for that purpose.
