### ISSUE TITLE
[suggestion]Avoid masking dplyr::select

### ISSUE THREAD

**Issue by WangYe661** [Bioconductor/AnnotationDbi#15]
loading this packages will mask dplyr::select which is much more frequently used, Maybe use a S3 generic function is a better way？

**Comment by hpages** [comment]
> loading this packages will mask dplyr::select which is much more frequently used

Maybe but `AnnotationDbi::select()` existed before **dplyr** was even born :smile: (2012 vs 2014)

> Maybe use a S3 generic function is a better way？

Unfortunately `dplyr::select()` and `AnnotationDbi::select()` have irreconcilable signatures so the conflict is unavoidable. 

Use `::` to disambiguate calls to `select()` in your code.

In an interactive session, using the **conflicted** package will help you disambiguate without the need to use the `::` syntax each time you call `select()`. Very convenient!

**Comment by WangYe661** [comment]
I got it, thank you very much
